# Generated by Django 4.1.7 on 2023-03-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngomodel',
            name='ngo_name',
        ),
    ]
