# Generated by Django 4.1.7 on 2023-03-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_ngomodel_ngo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ngoModel',
        ),
    ]
