# Generated by Django 4.1.7 on 2023-03-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_ngomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ngoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=50)),
                ('ngo_reg_id', models.CharField(max_length=50)),
                ('ngo_email', models.EmailField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('alt_phone_no', models.IntegerField()),
                ('address_street1', models.CharField(max_length=50)),
                ('address_street2', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Region', models.CharField(max_length=50)),
                ('Postal_code', models.IntegerField()),
                ('ngo_domain', models.CharField(max_length=50)),
            ],
        ),
    ]
