# Generated by Django 4.1.7 on 2023-03-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ngoModel',
            new_name='ngoModel2',
        ),
    ]
