# Generated by Django 4.1.7 on 2023-03-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_ngomodel_ngomodel2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ngoModel2',
            new_name='ngoModel',
        ),
    ]
