# Generated by Django 4.1.7 on 2023-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_ngomodel2_ngomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngomodel',
            name='ngo_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
