# Generated by Django 4.1.7 on 2023-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ngomodel_ngo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=50, null=True)),
                ('volunteer_email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('postalcode', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
    ]
