# Generated by Django 4.1.7 on 2023-03-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_volunteermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteermodel',
            old_name='domain',
            new_name='volunteer_domain',
        ),
    ]
