# Generated by Django 4.1.7 on 2023-03-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_domain_volunteermodel_volunteer_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteermodel',
            old_name='country',
            new_name='Country',
        ),
    ]
